<Project>
  <PropertyGroup>
    <BuildNumber Condition="'$(BuildNumber)' == ''">0.0</BuildNumber>
    <MajorVersion>9.59</MajorVersion>
    <Version>$(MajorVersion).$(BuildNumber)</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Publisher Condition="'$(Publisher)' == ''">CN=Contoso Ltd.</Publisher>
    <PublisherDisplayName Condition="'$(PublisherDisplayName)' == ''">Contoso Ltd.</PublisherDisplayName>
  </PropertyGroup>

  <PropertyGroup>
    <CommerceSdkPackagesVersion>[9.59.*-*,9.60)</CommerceSdkPackagesVersion>
    <CommercePosPackagesVersion>[9.59.*-*,9.60)</CommercePosPackagesVersion>
    <CommerceChannelPackagesVersion>[9.59.*-*,9.60)</CommerceChannelPackagesVersion>
    <CommerceHwsPackagesVersion>[9.59.*-*,9.60)</CommerceHwsPackagesVersion>
    <CommerceToolsPackagesVersion>[10.38.*-*,10.39)</CommerceToolsPackagesVersion>
    <CommercePaymentsPackagesVersion>[10.59.*-*,10.60)</CommercePaymentsPackagesVersion>
  </PropertyGroup>
</Project>
